---
- name: Deploy Docker Image
  hosts: client
  become: true
  vars:
    username: naveen2809
    password: Naveen@12#
  tasks:
    - name: Log into docker hub
      docker_login:
        username: "{{ username }}"
        password: "{{ password }}"
        reauthorize: yes

    - name: Run Docker Conatiner
      docker_container:        
        name: node-demo
        image: naveen2809/node-1:latest
        state: started
        pull: true
        ports:
        - "3005:3005"
        
    - name: Connect to docker container on port 8080 and check status 200 (Try 5 times)
      tags: test
      uri:
        url: http://localhost:3005
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 5